mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
# implement Google login
from django.contrib.auth.views import LogoutView

# handler404 = views.handler404
# handler500 = 'my_app.views.handler500'

urlpatterns = [
    path('studybuddy/', include('studybuddy.urls')),
    path('admin/', admin.site.urls),
    # implement Google login
    path('', views.index, name = "index"),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view(), name='logout'),
]

studybuddy/urls.py
from django.urls import path
from studybuddy.views import views, post_views, study_session_views, friend_views, room_views

app_name = 'studybuddy'
urlpatterns = [
    path('', views.index, name='index'),
    # implementing friends
    path('friends', friend_views.view_friends, name='viewFriends'),

    path('account/', views.account, name='account'),
    path('account/add/', views.addAccount, name='addAccount'),
    path('account/edit/', views.EditAccount, name='editAccount'),
    path('account/update/', views.UpdateAccount, name='updateAccount'),

    path('alldepartments/', views.alldepartments.as_view(), name='alldepartments'),
    path('rooms/', room_views.rooms, name='rooms'),
    path('rooms/<int:roomNumber>/', room_views.room, name='room'),
    path('<str:dept>/', views.department, name='department'),
    path('<str:dept>/<int:course_number>/', views.coursefeed, name ='coursefeed'),

    path('<str:dept>/<int:course_number>/makepost', post_views.makepost, name ='makepost'),
    path('viewpost', post_views.viewposts, name='viewposts'),

    path('<str:dept>/<int:course_number>/enroll', views.enrollcourse, name = 'enroll'),
    path('<str:dept>/<int:course_number>/updatecourseload', views.updatecourseload, name = 'ucl'),
    #path('<str:email>/<str:dept>/<int:course_number>/disenroll', views.enrollcourse, name = 'disenroll'),

    path('<int:roomNumber>/schedule', study_session_views.schedule, name='schedule'),
    path('upcomingSessions', study_session_views.upcomingSessions, name='upcomingSessions'),
]

templates/citations.html
{% comment %} This file is for the citations that Claire Yoon used (related to UX design) {% endcomment %}

{% comment %} /***************************************************************************************
*  Source 1:
*  Title: Background Image for Landing Page
*  Author: unsplash.com
*  URL: https://images.unsplash.com/photo-1629079447838-3d78840ee8cf?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1738&q=80
*  Usage: I used this image for the landing page.
*
*  Source 2:
*  Title: Bootstrap Profile Page
*  Author: BOOTSTRAPIOUS
*  Date: Published on 5/10/2019 and Last updated on 6/30/2019
*  URL: https://bootstrapious.com/p/bootstrap-profile-page
*  Usage: I used the combination of the color palette for all of the background except for the landing page.
*
*  Source 3:
*  Title: Bootstrap Profile Page Design
*  Author: Kshiti Ghelani
*  URL: https://bootsnipp.com/snippets/K0ZmK
*  Usage: I referenced this source code to create a form in studybuddy/templates/studybuddy/account.html file and
*         in studybuddy/templates/friends/friend_profiel.html file.
*
*  Source 4:
*  Title: CSS Text Animations - 6 tricks you should know in 2022
*  Author: Youtube channel "Keep coding"
*  URL: https://www.youtube.com/watch?v=V18Rvcxj1iA&t=2358s
*  Usage: I referenced this source code to use typewritter effect for our landing page title in /templates/index.html file
*
*  Source 5:
*  Title: Google Font
*  URL: https://www.w3schools.com/howto/tryit.asp?font=Orelega%20One
*  Usage: I used this font as our main font for the project. The font is used for the entire page.
***************************************************************************************/ {% endcomment %}

templates/index.html
{% load socialaccount %}
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="your name">
    <meta name="description" content="include some description about your page">
    <title>Study Buddy</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href='https://fonts.googleapis.com/css?family=Orelega One' rel='stylesheet'>
    <style>

      h1 {
        position: relative;
        color: white;
        font-family: 'Orelega One';
        font-size: 54px;
        letter-spacing: 6px;
        overflow: hidden;
        border-right: 2px solid hsl(0, 0%, 80%);
        white-space: nowrap;
        -webkit-text-stroke: 1px #464646;
        animation: typewriter 4s steps(44) 1s 1 normal both,
          blinkTextCursor 500ms infinite;
      }
      
      @keyframes typewriter {
        from {
          width: 0;
        }
        to {
          width: 920px;
        }
      }
      
      @keyframes blinkTextCursor {
        from {
          border-right-color: hsl(0, 0%, 80%);
        }
        to {
          border-right-color: transparent;
        }
      }

      body {
        padding: 0;
        margin: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        min-height: 100vh;
        font-family: 'Orelega One';
        font-size: 22px;
        min-height: 100vh;
        display: flex;
        flex-direction: column;
        max-width: 100%;
        max-height: 100%;
        background: url("https://images.unsplash.com/photo-1629079447838-3d78840ee8cf?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1738&q=80") no-repeat center;
        background-size: cover;
      }

      footer {
        padding: 15px;
        background-color: rgba(255, 255, 255, 0.2);
        margin-top: auto;
        color: #464646;
        position: absolute;
        bottom: 0;
        width: 100%;
      }
  
      @media only screen and (max-width: 768px) {
  
        /* For mobile phones and tablets: */
        [class*="col-"] {
          width: 100%;
        }
      }
  
      @media only screen and (min-width: 768px) {
        .col-1 {
          width: 8.33%;
        }
  
        .col-2 {
          width: 16.66%;
        }
  
        .col-3 {
          width: 25%;
        }
  
        .col-4 {
          width: 33.33%;
        }
  
        .col-5 {
          width: 41.66%;
        }
  
        .col-6 {
          width: 50%;
        }
  
        .col-7 {
          width: 58.33%;
        }
  
        .col-8 {
          width: 66.66%;
        }
  
        .col-9 {
          width: 75%;
        }
  
        .col-10 {
          width: 83.33%;
        }
  
        .col-11 {
          width: 91.66%;
        }
  
        .col-12 {
          width: 100%;
        }
      }

    .myForm .btn{
      font-size: 22px;
        margin-top: 10px;
        min-width: 140px;
        outline: none !important;
        background: rgba(222, 154, 255, 0.5);
        color: white;
        border-radius: 12px;
    }

    .myForm .btn:hover {
      font-size: 22px;
        margin-top: 10px;
        min-width: 140px;
        outline: none !important;
        background: rgba(156, 255, 168, 0.5);
        color: white;
        border-radius: 12px;
    }

    h2 {
      color: white;
      font-family: 'Orelega One';
      -webkit-text-stroke: 1px #464646;
    }

    </style>
  </head>
<body>
<h1>Do you want to study with me?</h1>
<h2>This website helps you to find study buddies!</h2>
{% if user.is_authenticated %}
  <p>Welcome, You are logged in as {{ user.username }}</p>
  <a href="{% url 'studybuddy:addAccount' %}">Go to Home Page</a>
{% else %}
<div class="myForm">
<form method="get">
  <button class="btn btn-lg" type="submit" formaction="{% provider_login_url 'google' %}">
    <a name="myBtn">Login with Google</a></button>
</form> 
</div>
{% endif %}
<footer class="footer-container">
  <div class="text-center">&copy; Team B-15</div>
</footer>
</body>
</html>