mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
# implement Google login
from django.contrib.auth.views import LogoutView

# handler404 = views.handler404
# handler500 = 'my_app.views.handler500'

urlpatterns = [
    path('studybuddy/', include('studybuddy.urls')),
    path('admin/', admin.site.urls),
    # implement Google login
    path('', views.index, name = "index"),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view(), name='logout'),
]

studybuddy/urls.py
from django.urls import path
from studybuddy.views import views, post_views, study_session_views, friend_views, room_views

app_name = 'studybuddy'
urlpatterns = [
    path('', views.index, name='index'),
    # implementing friends
    path('friends', friend_views.view_friends, name='viewFriends'),

    path('account/', views.account, name='account'),
    path('account/add/', views.addAccount, name='addAccount'),
    path('account/edit/', views.EditAccount, name='editAccount'),
    path('account/update/', views.UpdateAccount, name='updateAccount'),

    path('alldepartments/', views.alldepartments.as_view(), name='alldepartments'),
    path('rooms/', room_views.rooms, name='rooms'),
    path('rooms/<int:roomNumber>/', room_views.room, name='room'),
    path('<str:dept>/', views.department, name='department'),
    path('<str:dept>/<int:course_number>/', views.coursefeed, name ='coursefeed'),

    path('<str:dept>/<int:course_number>/makepost', post_views.makepost, name ='makepost'),
    path('viewpost', post_views.viewposts, name='viewposts'),

    path('<str:dept>/<int:course_number>/enroll', views.enrollcourse, name = 'enroll'),
    path('<str:dept>/<int:course_number>/updatecourseload', views.updatecourseload, name = 'ucl'),
    #path('<str:email>/<str:dept>/<int:course_number>/disenroll', views.enrollcourse, name = 'disenroll'),

    path('<int:roomNumber>/schedule', study_session_views.schedule, name='schedule'),
    path('upcomingSessions', study_session_views.upcomingSessions, name='upcomingSessions'),
]

studybuddy/models.py
import datetime
from django.db import models
from django.utils import timezone


# Create your models here.
class User(models.Model):
    email = models.CharField(primary_key=True, max_length=30, default="")
    # firstName = models.CharField(max_length=30, default="")
    # lastName = models.CharField(max_length=30, default="")
    username = models.CharField(max_length=30, default="")
    name = models.CharField(max_length=50, default="")
    major = models.CharField(max_length=50, default="")
    zoomLink = models.URLField(max_length=300, default="")
    blurb = models.TextField(default="")

    # implementing friends
    friends = models.ManyToManyField("self")
    username = models.CharField(max_length=30, default="")

    def __str__(self):
        return self.email


# implementing friends
class Friend_Request(models.Model):
    from_user = models.ForeignKey(User, related_name='from_user', on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name='to_user', on_delete=models.CASCADE)
    declined = models.TextField('no')

    def __str__(self):
        return self.from_user.email


class Departments(models.Model):
    dept = models.CharField(max_length=4)

    def __str__(self):
        return self.dept


class Course(models.Model):
    subject = models.CharField(max_length=4)
    catalog_number = models.CharField(max_length=4)
    instructor = models.CharField(max_length=100)
    section = models.CharField(max_length=4)
    course_number = models.CharField(max_length=10)
    description = models.TextField(default="")

    class Meta:
        unique_together = ["subject", "catalog_number", "instructor", "section", "course_number", "description"]

    def class_str(self):
        course_level = self.subject + str(self.catalog_number)
        return course_level + ": " + self.description

    def __str__(self):
        course_level = self.subject + str(self.catalog_number)
        if self.instructor == '-':
            inst = "Not available"
        else:
            inst = self.instructor
        instructor = "Instructor: " + inst
        section = "(Section: " + str(self.section) + ")"
        return course_level + ": " + self.description + " \n " + instructor + " \n " + section


class Post(models.Model):
    """
    Foreign Key means: one post can only be related to more than one course
    we want this so we can relate posts to more than one section

    Note: change to models.OneToOneField if we want to have a post only be related to one course

    Source for on_delete: https://stackoverflow.com/questions/38388423/what-does-on-delete-do-on-django-models
        we want to remove posts related to the course and/or user when a post is delete, so we are using using CASCADE
    """
    course = models.ForeignKey(Course, on_delete=models.CASCADE, )
    user = models.ForeignKey(User, on_delete=models.CASCADE, )
    author = models.CharField(max_length=30, default="Author of this post chose to be anonymous")
    topic = models.CharField(max_length=100, default="No topic was provided by the author of this post")
    startDate = models.DateField(default=timezone.now().strftime("%Y-%m-%d"))
    endDate = models.DateField(default=(timezone.now() + datetime.timedelta(days=7)).strftime("%Y-%m-%d"))
    description = models.TextField(default="No description was provided by the author of this post")
    post_type = models.TextField(default="section")

    def past_end_date(self):
        now = timezone.now()
        # returns true if endDate has passed
        # returns false if endDate is still valid
        return now > self.endDate

    def __str__(self):
        author = "Author: " + self.author
        if type(self.startDate) != str:
            time_frame = self.startDate.strftime("%m-%d-%Y") + " to " + self.endDate.strftime(
                "%m-%d-%Y")
        else:
            time_frame = self.startDate + " to " + self.endDate

        return self.topic + '\n' + author + '\n' + time_frame + '\n'


class EnrolledClass(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.course.subject + " " + self.course.course_number


class Room(models.Model):
    name = models.CharField(max_length=255)
    post = models.OneToOneField(Post, on_delete=models.CASCADE)
    users = models.ManyToManyField(User)

    def __str__(self):
        course_name = self.post.course.subject + str(self.post.course.catalog_number)
        course_description = self.post.course.description
        topic = 'Topic: ' + self.name
        # return course_name + ': ' + course_description + '\n' + topic
        return course_name + ' - ' + self.name


class Message(models.Model):
    room = models.ForeignKey(Room, related_name='messages', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date_added',)


class StudySession(models.Model):
    """
    a study session is associated with a post
    """
    # if post is deleted, the study session should still remain, because deletion of a post means
    # the user no longer wants the post/they have found a study buddy, but study sessions schedule should remain
    post = models.ForeignKey(Post, on_delete=models.SET_NULL, null=True)
    users = models.ManyToManyField(User)
    # If the author of the study session is removed the system, their study sessions should also be removed
    author = models.CharField(max_length=100)

    # currently just setting it the room name
    name = models.CharField(max_length=50, default="Study Session")  # update after figuring out room/post/user relation
    date = models.DateField(default=timezone.now().strftime("%m-%d-%Y"))
    start = models.TimeField(default=timezone.now().strftime("%H-%M"))
    end = models.TimeField(default=(timezone.now() + datetime.timedelta(hours=1)).strftime("%H-%M"))
    accepted = models.CharField(max_length=4, default="?")

    def __str__(self):
        if type(self.start) != str:
            time_frame = "Time Frame: " + self.start.strftime("%H:%M") + " to " + self.end.strftime("%H:%M")
        else:
            time_frame = "Time Frame: " + self.start + " to " + self.start

        if type(self.date) != str:
            date = "Scheduled on: " + self.date.strftime("%m-%d-%Y")
        else:
            date = "Scheduled on: " + self.date

        name = "Study session for: " + self.name

        return name + '\n' + date + '\n' + time_frame

studybuddy/views/friend_views.py
from django.shortcuts import render
from studybuddy.models import User, Friend_Request


def send_friend_request(request, requestee_email):
    '''
    return 0: friend request was already sent and is pending approval
           1: friend request was created and sent
           2: the 2 users are already friends
    '''

    # This method is called after already processing to and from users are valid
    from_user = User.objects.get(email__exact=request.user.email)
    to_user = User.objects.get(email__exact=requestee_email)

    if from_user.friends.all().filter(email=requestee_email):
        return 2

    friend_request, created = Friend_Request.objects.get_or_create(from_user=from_user, to_user=to_user)
    if created:
        return 1
    else:
        return 0


def accept_friend_request(request, requester_email):
    """
    return 0: friend request doesn't exist/already accepted
           1: friend request successfully accepted
    """
    from_user = User.objects.get(email=requester_email)
    to_user = User.objects.get(email=request.user.email)

    friend_request_query_set = Friend_Request.objects.filter(from_user=from_user).filter(to_user=to_user)
    friend_request = friend_request_query_set.first()

    if friend_request:
        friend_request.to_user.friends.add(friend_request.from_user)
        print(friend_request.to_user.friends.all())
        friend_request.from_user.friends.add(friend_request.to_user)
        print(friend_request.from_user.friends.all())
        friend_request.delete()
        return 1
    else:
        return 0


def remove_friend(request, email):
    User.objects.get(email=request.user.email).friends.remove(User.objects.get(email=email))


def decline_request(request, email):
    """
    this method is called with the request.user is trying to delete a friend request
    parameters: email - the email of the user that sent the friend request
    """
    from_user = User.objects.get(email=email)
    to_user = User.objects.get(email=request.user.email)

    Friend_Request.objects.filter(from_user=from_user).filter(to_user=to_user).delete()


def view_friends(request):
    if request.user.is_anonymous:
        return render(request, template_name="index.html")

    from_user = User.objects.get(email=request.user.email)
    # get the friend requests that are sent to the current user
    friend_request = Friend_Request.objects.filter(to_user=from_user)
    sent_requests = Friend_Request.objects.filter(from_user=from_user)
    friends = from_user.friends.all()

    context = {
        'friends': friends,
        'friend_requests': friend_request,
        'sent_requests': sent_requests,
        'student_name': from_user.name,
        # add declined?
    }

    if from_user.name == "":
        context['student_name'] = request.user

    # if the user sent a friend request
    if request.POST.get('request'):
        requestee_email = request.POST.get('email')
        context['toEmail'] = requestee_email
        # make sure the user isn't trying to add themselves
        if requestee_email == request.user.email:
            context['self'] = True
        # check that the requested friend is in our system
        elif User.objects.filter(email__exact=requestee_email).exists():
            # send the request (adds to friend_request model)
            send = send_friend_request(request, requestee_email)

            # if returned 1, means the friend request was created
            if send == 1:
                context['sent'] = True
            elif send == 2:
                context['already_friends'] = True
            # else it returned a 0 meaning the friend request was already pending
            else:
                context['alreadySent'] = True

        # if the user isn't in our system let the user know
        else:
            context['notValid'] = True

    # user accepted a friend request
    if request.POST.get('accept'):
        ad_email = request.POST.get('ad_email')
        accepted = accept_friend_request(request, ad_email)
        if accepted:
            context['accepted'] = True
            context['accepted_email'] = ad_email

    if request.POST.get('decline'):
        ad_email = request.POST.get('ad_email')
        decline_request(request, ad_email)
        context['declined'] = True
        context['declined_email'] = ad_email

    if request.POST.get('unfriend'):
        remove_email = request.POST.get('remove_email')
        remove_friend(request, remove_email)
        context['remove_friend'] = True
        context['removed_email'] = remove_email

    if request.POST.get('view_friends'):
        friend_email = request.POST.get('friend_email')
        request.POST = None
        return view_friend_profile(request, friend_email)

    request.POST = None
    return render(request, "friends/view_friends.html", context)


def view_friend_profile(request, friend_email):
    friend = User.objects.get(email__exact=friend_email)

    context = {
        'student': User.objects.get(email=request.user.email),
        'student_name': User.objects.get(email=request.user.email).name,
        'friend': friend
    }

    if User.objects.get(email=request.user.email).name == "":
        context['student_name'] = request.user

    return render(request, "friends/friend_profile.html", context)

studybuddy/views/room_views.py
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponseRedirect
from studybuddy.models import Room, Message, User, Post


def rooms(request):
    if request.user.is_anonymous:
        return render(request, template_name="index.html")

    context = {
        'rooms': Room.objects.filter(users=User.objects.get(email=request.user.email)),
        'student_name': User.objects.get(email=request.user.email).name,
    }

    if User.objects.get(email=request.user.email).name == "":
        context['student_name'] = request.user

    return render(request, 'studybuddy/rooms.html', context)


def room(request, roomNumber):
    if request.user.is_anonymous:
        return render(request, template_name="index.html")

    if request.POST.get('leave'):
        room_pk = request.POST['room_pk']
        if Room.objects.filter(pk=room_pk):
            room = Room.objects.get(pk=room_pk)
            if room.users.count() == 1:
                room.delete()
            else:
                room.users.remove(User.objects.get(email=request.user.email))
        return HttpResponseRedirect(reverse('studybuddy:rooms'))

    context = {
        'username': User.objects.get(email=request.user.email).username,
        'student_name': User.objects.get(email=request.user.email).name,
    }

    if Room.objects.filter(pk=roomNumber):
        if Room.objects.get(pk=roomNumber).users.all().filter(email=request.user.email):
            room = Room.objects.get(pk=roomNumber)
            context['room'] = room
            messages = Message.objects.filter(room=room)[:25]
            context['messages'] = messages
        else:
            context['notMember'] = True
    else:
        context['noRoom'] = True

    if User.objects.get(email=request.user.email).name == "":
        context['student_name'] = request.user

    return render(request, 'studybuddy/room.html', context)


def addRoom(request):
    post_pk = request.POST['post_pk']
    post = Post.objects.get(pk=post_pk)
    # If there is no rooms current associated to this room, make a new room
    if not Room.objects.filter(post=post):
        # create a new object with the owner of the post
        Room.objects.create(post=post, name=post.topic)
        Room.objects.get(post=post).users.add(User.objects.get(email=post.user.email))
        # add the new user who wants to join to the room
    # add the new user into the room (this will happen after a new made room or just added to the already existing room)
    Room.objects.get(post=post).users.add(User.objects.get(email=request.user.email))

    # return room(request, roomNumber=Room.objects.get(post=post).pk)
    return Room.objects.get(post=post).pk

studybuddy/templates/studybuddy/account.html
{% load socialaccount %}
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Team B-15">
        <meta name="description" content="Study Buddy">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
            integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <title>Study Buddy</title>
        <link href='https://fonts.googleapis.com/css?family=Orelega One' rel='stylesheet'>
        <style>
            .navbar {
                text-align: right;
                background-color: rgba(255, 255, 255, 0.3);
                color: #464646;
            }

            .navbar-brand {
                margin-left: 16px;
                font-size: 26px;
                color: #464646;
            }

            .navbar-toggler {
                color: #464646;
            }

            .nav-link {
                text-align: right;
                color: #464646;
            }

            footer {
                padding: 15px;
                background-color: rgba(255, 255, 255, 0.3);
                margin-top: auto;
                left: 0;
                right: 0;
                width: 100%;
                color: #464646;
                bottom: 0;
                position: positive relative;
            }

            @media only screen and (max-width: 768px) {

                /* For mobile phones and tablets: */
                [class*="col-"] {
                    width: 100%;
                }
            }

            @media only screen and (min-width: 768px) {
                .col-1 {
                    width: 8.33%;
                }

                .col-2 {
                    width: 16.66%;
                }

                .col-3 {
                    width: 25%;
                }

                .col-4 {
                    width: 33.33%;
                }

                .col-5 {
                    width: 41.66%;
                }

                .col-6 {
                    width: 50%;
                }

                .col-7 {
                    width: 58.33%;
                }

                .col-8 {
                    width: 66.66%;
                }

                .col-9 {
                    width: 75%;
                }

                .col-10 {
                    width: 83.33%;
                }

                .col-11 {
                    width: 91.66%;
                }

                .col-12 {
                    width: 100%;
                }
            }

            .container .myForm .nav-tabs{
                margin-bottom: 3%;
            }
            .container .myForm .nav-tabs .nav-link{
                font-weight:600;
                border: none;
            }
            .container .myForm .nav-tabs .nav-link.active{
                font-size: 20px;
                border: none;
                border-bottom:2px solid #0062cc;
            }

            body {
                font-family: 'Orelega One';
                font-size: 18px;
                min-height: 100vh;
                display: flex;
                flex-direction: column;
                max-width: 100%;
                max-height: 100%;
                background: #654ea3;
                background: -webkit-linear-gradient(to right, #654ea3, #eaafc8);
                background: linear-gradient(to right, #654ea3, #eaafc8);
                background-size: cover;
                background-position: 30%;
                background-attachment: fixed;
            }

            .container {
                position: relative;
                max-width: 1140px;
                padding: 3%;
                margin-top: 3%;
                margin-bottom: 3%;
                border-radius: 20px;
                background: #fff;
            }

            .profile-work{
                padding: 15%;
                margin-top: -15%;
                margin-bottom: -15%;
            }
            .profile-work p{
                font-size: 12px;
                color: #818182;
            }

            .profile-work a{
                text-decoration: none;
                color: #495057;
                font-size: 20px;
            }

            .profile-work ul{
                list-style: none;
            }
            .profile-tab label{
            }

            .profile-tab p{
                font-size: 22px;
                color: #0062cc;
            }

            .profile-tab label{
                font-size: 22px;
            }

            .myForm .btn{
                font-size: 22px;
                  min-width: 140px;
                  outline: none !important;
                  background: #aaa6e2;
                  color: white;
                  border-radius: 12px;
              }

              .myForm .btn:hover {
                font-size: 22px;
                  min-width: 140px;
                  outline: none !important;
                  background: #a6e2c8;
                  color: white;
                  border-radius: 12px;
              }

              .profile-work .btn {
                margin-top: 15px;
                font-size: 18px;
                  min-width: 140px;
                  outline: none !important;
                  background: #aaa6e2;
                  color: white;
                  border-radius: 12px;
              }

              .profile-work .btn:hover {
                margin-top: 15px;
                font-size: 18px;
                  min-width: 140px;
                  outline: none !important;
                  background: #a6e2c8;
                  color: white;
                  border-radius: 12px;
              }

              .container .row {
                word-wrap: break-word;
              }

              .container .profile-work .text{
                color: #949494;
              }
        </style>
    </head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <div class="row">
    <nav class="navbar navbar-expand-md navbar-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'studybuddy:index' %}"> Study Buddy</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#collapsibleNavbar" aria-controls="collapsibleNavbar" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="{% url 'studybuddy:viewposts' %}">My Posts</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'studybuddy:alldepartments' %}"> Update Course Schedule </a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'studybuddy:upcomingSessions' %}"> Study Sessions</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'studybuddy:rooms' %}"> Chat Room </a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'studybuddy:viewFriends' %}">Friends</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'studybuddy:account' %}"> My Account </a></li>
                    <li class="nav-item"><a class="nav-link" href="/logout"> Logout {{student_name}} </a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>
    <div class="container">
        <div class="col-md-12">
        <form class = "myForm">

                <div>
                            <h1>
                                {{Name}}
                                <a href="{% url 'studybuddy:editAccount' %}" name="myBtn" class="btn btn-sm">Edit Profile</a>
                            </h1>
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active">About me</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <div class="profile-work">
                        <p><h3>My Schedule</h3></p>
                        {% if student.enrolledclass_set.all %}
                            {% for class in student.enrolledclass_set.all %}
                                <li>
                                    <a href="{% url 'studybuddy:coursefeed' class.course.subject class.course.course_number%}">
                                        {{ class.course.subject }} {{ class.course.catalog_number }} - Section: {{ class.course.section }}
                                    </a>
                                </li>
                            {% endfor %}
                        {% else %}
                            <h5 class="text">You currently do not have any classes added to your schedule</h5>
                        {% endif %}
                        <a name="myBtn" class="btn btn-sm" href="{% url 'studybuddy:alldepartments'%}">Edit Schedule</a>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="tab-content profile-tab" id="myTabContent">
                        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Username</label>
                                        </div>
                                        <div class="col-md-6">
                                            <p>{{UserName}}</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Name</label>
                                        </div>
                                        <div class="col-md-6">
                                            <p>{{Name}}</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Email</label>
                                        </div>
                                        <div class="col-md-6">
                                            <p>{{Email}}</p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label>Major</label>
                                        </div>
                                        <div class="col-md-6">
                                            <p>{{Major}}</p>
                                        </div>
                                    </div>
                                    
                        </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <label>Zoom Link</label><br/>
                                    <p><a href="{{ZoomLink}}">{{ZoomLink}}</a></p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <label>Introduction</label><br/>
                                    <p>{{Introduction}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            </div>
    </div>

      <footer class="footer-container">
        <div class="text-center">&copy; Team B-15</div>
      </footer>
</body>
</html>